version: '3.8'

services:
  api:
    container_name: app-builder-server
    build:
      dockerfile: Dockerfile
      context: "./app"
    volumes:
      - /app/node_modules
      - ./app:/app
    ports:
      - 5002:5002
    
  client:
    container_name: app-builder-client
    build:
      dockerfile: Dockerfile
      context: ./app-builder
    volumes:
      - /app/node_modules
      - ./app-builder:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true